FROM ubuntu:14.04

RUN apt-get update && \
  apt-get -y install ruby ruby-dev rubygems-integration make gcc rpm git wget curl && \
  gem install fpm --no-rdoc --no-ri

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /root

ADD <%= filename %> /root/
ADD recipe /root/recipe
CMD bash /root/<%= filename %>
